# Analysis of FetaQA Data

In [1]:

import pandas as pd

# Load the CoT CSV file
cot_file_path = '/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/fetaqa/fetaqa_cot_results.csv'
cot_results_df = pd.read_csv(cot_file_path)

# Display basic information and the first few rows of the dataframe
cot_results_df.info()
cot_results_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1582 entries, 0 to 1581
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           1582 non-null   int64
 1   Unnamed: 0             1582 non-null   int64
 2   index                  1582 non-null   int64
 3   table_id               1582 non-null   object
 4   question               1582 non-null   object
 5   response               1582 non-null   object
 6   answer                 1579 non-null   object
 7   output                 1581 non-null   object
 8   conv_actual_answer     1579 non-null   object
 9   conv_predicted_answer  1581 non-null   object
 10  f1_score               1582 non-null   float64
 11  exact                  1582 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 148.4+ KB

,Unnamed: 0.1,Unnamed: 0,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,0,0,0,totto_source/dev_json/example-2205.json,What TV shows was Shagun Sharma seen in 2019?,Reasoning: To determine the TV shows Shagun Sh...,"In 2019, Shagun Sharma played in the roles as ...","[""Laal Ishq"", ""Vikram Betaal Ki Rahasya Gatha""...","in 2019, shagun sharma played in the roles as ...","[laal ishq, vikram betaal ki rahasya gatha, sh...",57.142857,0.0
1,1,1,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,Reasoning: To determine the voting results of ...,In the 1975 North Vietnamese legislative elect...,424 seats \n,in the 1975 north vietnamese legislative elect...,424 seats,26.666667,0.0
2,2,2,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,Reasoning: To determine the roles Christian Co...,"During 2009, Christian Cooke played the lead r...","""Luke Rutherford-Van Helsing"", ""Lord Dorian Ga...","during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0
3,3,3,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,Reasoning: To determine when and where Kazunar...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0
4,4,4,4,totto_source/dev_json/example-430.json,Who set the fastest average in Megaminx?,Reasoning: To find who set the fastest average...,The 32.03 seconds average of five solves is se...,Yu Da-Hyun \n,the 32.03 seconds average of 5 solves is set b...,yu da-hyun,22.222222,0.0

In [2]:

# Remove redundant index columns
cleaned_cot_results_df = cot_results_df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

# Display basic information of the cleaned dataframe
cleaned_cot_results_df.info()
cleaned_cot_results_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1582 entries, 0 to 1581
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   index                  1582 non-null   int64
 1   table_id               1582 non-null   object
 2   question               1582 non-null   object
 3   response               1582 non-null   object
 4   answer                 1579 non-null   object
 5   output                 1581 non-null   object
 6   conv_actual_answer     1579 non-null   object
 7   conv_predicted_answer  1581 non-null   object
 8   f1_score               1582 non-null   float64
 9   exact                  1582 non-null   float64
dtypes: float64(2), int64(1), object(7)
memory usage: 123.7+ KB

,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,0,totto_source/dev_json/example-2205.json,What TV shows was Shagun Sharma seen in 2019?,Reasoning: To determine the TV shows Shagun Sh...,"In 2019, Shagun Sharma played in the roles as ...","[""Laal Ishq"", ""Vikram Betaal Ki Rahasya Gatha""...","in 2019, shagun sharma played in the roles as ...","[laal ishq, vikram betaal ki rahasya gatha, sh...",57.142857,0.0
1,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,Reasoning: To determine the voting results of ...,In the 1975 North Vietnamese legislative elect...,424 seats \n,in the 1975 north vietnamese legislative elect...,424 seats,26.666667,0.0
2,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,Reasoning: To determine the roles Christian Co...,"During 2009, Christian Cooke played the lead r...","""Luke Rutherford-Van Helsing"", ""Lord Dorian Ga...","during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0
3,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,Reasoning: To determine when and where Kazunar...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0
4,4,totto_source/dev_json/example-430.json,Who set the fastest average in Megaminx?,Reasoning: To find who set the fastest average...,The 32.03 seconds average of five solves is se...,Yu Da-Hyun \n,the 32.03 seconds average of 5 solves is set b...,yu da-hyun,22.222222,0.0

In [3]:

# Load the Decomposition CSV file
decomp_file_path = '/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/fetaqa/fetaqa_decomposition_results.csv'
decomp_results_df = pd.read_csv(decomp_file_path)

# Display basic information and the first few rows of the dataframe
decomp_results_df.info()
decomp_results_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1582 entries, 0 to 1581
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0.1           1582 non-null   int64
 1   Unnamed: 0             1582 non-null   int64
 2   index                  1582 non-null   int64
 3   table_id               1582 non-null   object
 4   question               1582 non-null   object
 5   response               1582 non-null   object
 6   answer                 1579 non-null   object
 7   output                 1580 non-null   object
 8   conv_actual_answer     1579 non-null   object
 9   conv_predicted_answer  1580 non-null   object
 10  f1_score               1582 non-null   float64
 11  exact                  1582 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 148.4+ KB

,Unnamed: 0.1,Unnamed: 0,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,0,0,0,totto_source/dev_json/example-2205.json,What TV shows was Shagun Sharma seen in 2019?,"```json\n{\n ""decomposition"": {\n ""sq1"": ""Ide...","In 2019, Shagun Sharma played in the roles as ...","Laal Ishq, Vikram Betaal Ki Rahasya Gatha, Sha...","in 2019, shagun sharma played in the roles as ...","laal ishq, vikram betaal ki rahasya gatha, sha...",57.142857,0.0
1,1,1,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,"```json\n{\n ""decomposition"": {\n ""sq1"": ""Ide...",In the 1975 North Vietnamese legislative elect...,424 seats \n,in the 1975 north vietnamese legislative elect...,424 seats,26.666667,0.0
2,2,2,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,"```json\n{\n ""decomposition"": {\n ""sq1"": ""Wha...","During 2009, Christian Cooke played the lead r...","Luke Rutherford-Van Helsing, Lord Dorian Gauda...","during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0
3,3,3,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,decomposition: |\n sq1. Identify the row ...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0
4,4,4,4,totto_source/dev_json/example-430.json,Who set the fastest average in Megaminx?,decomposition: |\n sq1: What is the name ...,The 32.03 seconds average of five solves is se...,Yu Da-Hyun \n,the 32.03 seconds average of 5 solves is set b...,yu da-hyun,22.222222,0.0

In [4]:

# Remove redundant index columns
cleaned_decomp_results_df = decomp_results_df.drop(columns=['Unnamed: 0.1', 'Unnamed: 0'])

# Display basic information of the cleaned dataframe
cleaned_decomp_results_df.info()
cleaned_decomp_results_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1582 entries, 0 to 1581
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   index                  1582 non-null   int64
 1   table_id               1582 non-null   object
 2   question               1582 non-null   object
 3   response               1582 non-null   object
 4   answer                 1579 non-null   object
 5   output                 1580 non-null   object
 6   conv_actual_answer     1579 non-null   object
 7   conv_predicted_answer  1580 non-null   object
 8   f1_score               1582 non-null   float64
 9   exact                  1582 non-null   float64
dtypes: float64(2), int64(1), object(7)
memory usage: 123.7+ KB

,index,table_id,question,response,answer,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,0,totto_source/dev_json/example-2205.json,What TV shows was Shagun Sharma seen in 2019?,"```json\n{\n ""decomposition"": {\n ""sq1"": ""Ide...","In 2019, Shagun Sharma played in the roles as ...","Laal Ishq, Vikram Betaal Ki Rahasya Gatha, Sha...","in 2019, shagun sharma played in the roles as ...","laal ishq, vikram betaal ki rahasya gatha, sha...",57.142857,0.0
1,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,"```json\n{\n ""decomposition"": {\n ""sq1"": ""Ide...",In the 1975 North Vietnamese legislative elect...,424 seats \n,in the 1975 north vietnamese legislative elect...,424 seats,26.666667,0.0
2,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,"```json\n{\n ""decomposition"": {\n ""sq1"": ""Wha...","During 2009, Christian Cooke played the lead r...","Luke Rutherford-Van Helsing, Lord Dorian Gauda...","during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0
3,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,decomposition: |\n sq1. Identify the row ...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0
4,4,totto_source/dev_json/example-430.json,Who set the fastest average in Megaminx?,decomposition: |\n sq1: What is the name ...,The 32.03 seconds average of five solves is se...,Yu Da-Hyun \n,the 32.03 seconds average of 5 solves is set b...,yu da-hyun,22.222222,0.0

In [5]:

# Load the Meta CSV file
meta_file_path = '/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/fetaqa/fetaqa_meta_results.csv'
meta_results_df = pd.read_csv(meta_file_path)

# Display basic information and the first few rows of the dataframe
meta_results_df.info()
meta_results_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1581 entries, 0 to 1580
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             1581 non-null   int64
 1   index                  1581 non-null   int64
 2   table_id               1581 non-null   object
 3   question               1581 non-null   object
 4   response               1581 non-null   object
 5   answer                 1578 non-null   object
 6   answer_extraction      1581 non-null   object
 7   output                 1581 non-null   object
 8   conv_actual_answer     1578 non-null   object
 9   conv_predicted_answer  1581 non-null   object
 10  f1_score               1581 non-null   float64
 11  exact                  1581 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 148.3+ KB

,Unnamed: 0,index,table_id,question,response,answer,answer_extraction,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,0,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,**Problem Understanding:**\n1. **Determine the...,In the 1975 North Vietnamese legislative elect...,"Vietnamese Fatherland Front, 424 seats \n",NONE,in the 1975 north vietnamese legislative elect...,"vietnamese fatherland front, 424 seats",55.555556,0.0
1,1,5,totto_source/train_json/example-13152.json,What seasons did Faye appear for Hull City?,**Problem Understanding:**\n1. **Determine the...,Faye appeared for Hull City in the 2012–13 and...,"2012–13, 2013–14 \n",NONE,faye appeared for hull city in the 2012-13 and...,"2012-13, 2013-2014",16.666667,0.0
2,2,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,**Problem Understanding:**\n1. **Determine the...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",NONE,kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0
3,3,18,totto_source/train_json/example-2382.json,What roles did Sandra Peabody play in Tarot an...,**Problem Understanding:**\n1. Determine the O...,Peabody appeared as The Sun in an Off-Broadway...,"""The Sun"", ""Minnie"" \n",NONE,peabody appeared as the sun in an off-broadway...,"the sun, minnie",18.181818,0.0
4,4,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,**Problem Understanding:**\n1. Determine the O...,"During 2009, Christian Cooke played the lead r...","""Luke Rutherford-Van Helsing"", ""Lord Dorian Ga...",NONE,"during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0

In [6]:

# Remove redundant index columns
cleaned_meta_results_df = meta_results_df.drop(columns=['Unnamed: 0'])

# Display basic information of the cleaned dataframe
cleaned_meta_results_df.info()
cleaned_meta_results_df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1581 entries, 0 to 1580
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   index                  1581 non-null   int64
 1   table_id               1581 non-null   object
 2   question               1581 non-null   object
 3   response               1581 non-null   object
 4   answer                 1578 non-null   object
 5   answer_extraction      1581 non-null   object
 6   output                 1581 non-null   object
 7   conv_actual_answer     1578 non-null   object
 8   conv_predicted_answer  1581 non-null   object
 9   f1_score               1581 non-null   float64
 10  exact                  1581 non-null   float64
dtypes: float64(2), int64(1), object(8)
memory usage: 136.0+ KB

,index,table_id,question,response,answer,answer_extraction,output,conv_actual_answer,conv_predicted_answer,f1_score,exact
0,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,**Problem Understanding:**\n1. **Determine the...,In the 1975 North Vietnamese legislative elect...,"Vietnamese Fatherland Front, 424 seats \n",NONE,in the 1975 north vietnamese legislative elect...,"vietnamese fatherland front, 424 seats",55.555556,0.0
1,5,totto_source/train_json/example-13152.json,What seasons did Faye appear for Hull City?,**Problem Understanding:**\n1. **Determine the...,Faye appeared for Hull City in the 2012–13 and...,"2012–13, 2013–14 \n",NONE,faye appeared for hull city in the 2012-13 and...,"2012-13, 2013-2014",16.666667,0.0
2,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,**Problem Understanding:**\n1. **Determine the...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",NONE,kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0
3,18,totto_source/train_json/example-2382.json,What roles did Sandra Peabody play in Tarot an...,**Problem Understanding:**\n1. Determine the O...,Peabody appeared as The Sun in an Off-Broadway...,"""The Sun"", ""Minnie"" \n",NONE,peabody appeared as the sun in an off-broadway...,"the sun, minnie",18.181818,0.0
4,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,**Problem Understanding:**\n1. Determine the O...,"During 2009, Christian Cooke played the lead r...","""Luke Rutherford-Van Helsing"", ""Lord Dorian Ga...",NONE,"during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0

In [7]:

# Function to summarize the method used in the 'response' column
def summarize_method(response):
    response_lower = response.lower()
    steps = [
        "Identify the objective of the question",
        "Determine the relevant information or data needed from the table",
        "Break down the question into sub-questions or specific tasks",
        "Extract necessary details from the table to answer each sub-question",
        "Compile and synthesize the extracted information to form the final answer"
    ]
    
    if all(step.lower() in response_lower for step in steps):
        summary = [
            "Identify the objective of the question and determine relevant information needed.",
            "Break down the question into sub-questions and extract necessary details from the table.",
            "Compile and synthesize the extracted information to form the final answer."
        ]
    else:
        summary = [
            "Problem understanding and identifying relevant information.",
            "Systematic extraction of details and answering sub-questions.",
            "Combining answers to form a comprehensive final response."
        ]
        
    return "\n".join(summary)

# Apply the summarization function to each row
cleaned_meta_results_df['method_summary'] = cleaned_meta_results_df['response'].apply(summarize_method)

# Display the dataframe with the method summary
cleaned_meta_results_df.head()

,index,table_id,question,response,answer,answer_extraction,output,conv_actual_answer,conv_predicted_answer,f1_score,exact,method_summary
0,1,totto_source/train_json/example-7854.json,What were the voting results of the 1975 North...,**Problem Understanding:**\n1. **Determine the...,In the 1975 North Vietnamese legislative elect...,"Vietnamese Fatherland Front, 424 seats \n",NONE,in the 1975 north vietnamese legislative elect...,"vietnamese fatherland front, 424 seats",55.555556,0.0,Problem understanding and identifying relevant...
1,5,totto_source/train_json/example-13152.json,What seasons did Faye appear for Hull City?,**Problem Understanding:**\n1. **Determine the...,Faye appeared for Hull City in the 2012–13 and...,"2012–13, 2013–14 \n",NONE,faye appeared for hull city in the 2012-13 and...,"2012-13, 2013-2014",16.666667,0.0,Problem understanding and identifying relevant...
2,3,totto_source/train_json/example-13717.json,When and in which club and league did Kazunari...,**Problem Understanding:**\n1. **Determine the...,Kazunari Okayama joined J1 League club Yokoham...,"1997, Yokohama Marinos, J1 League \n",NONE,kazunari okayama joined j1 league club yokoham...,"1997, yokohama marinos, j1 league",52.631579,0.0,Problem understanding and identifying relevant...
3,18,totto_source/train_json/example-2382.json,What roles did Sandra Peabody play in Tarot an...,**Problem Understanding:**\n1. Determine the O...,Peabody appeared as The Sun in an Off-Broadway...,"""The Sun"", ""Minnie"" \n",NONE,peabody appeared as the sun in an off-broadway...,"the sun, minnie",18.181818,0.0,Problem understanding and identifying relevant...
4,2,totto_source/dev_json/example-560.json,What roles did Christian Cooke play in 2009?,**Problem Understanding:**\n1. Determine the O...,"During 2009, Christian Cooke played the lead r...","""Luke Rutherford-Van Helsing"", ""Lord Dorian Ga...",NONE,"during 2009, christian cooke played the lead r...","luke rutherford-van helsing, lord dorian gaudain",34.782609,0.0,Problem understanding and identifying relevant...

In [8]:

# Select only the necessary columns
filtered_meta_results_df = cleaned_meta_results_df[['question', 'response', 'f1_score']]

# Assuming CoT and Decomposition responses are from previously loaded data
filtered_cot_results_df = cleaned_cot_results_df[['question', 'response']].rename(columns={'response': 'cot_response'})
filtered_decomp_results_df = cleaned_decomp_results_df[['question', 'response']].rename(columns={'response': 'decomp_response'})

# Merge the dataframes on the 'question' column
merged_results_df = filtered_meta_results_df.merge(filtered_cot_results_df, on='question', how='left')
merged_results_df = filtered_results_df.merge(filtered_decomp_results_df, on='question', how='left')

# Add the 'answer' column from Meta DataFrame
merged_results_df['answer'] = cleaned_meta_results_df['answer']

# Add the F1 score of Meta
merged_results_df['meta_f1_score'] = cleaned_meta_results_df['f1_score']

# Display the merged dataframe
merged_results_df.head()

NameError: name 'filtered_results_df' is not defined

In [9]:

# Filter the rows where Meta has higher F1 scores compared to CoT and Decomposition
higher_f1_meta_df = merged_results_df[
    (merged_results_df['meta_f1_score'] > merged_results_df['cot_f1_score']) & 
    (merged_results_df['meta_f1_score'] > merged_results_df['decomp_f1_score'])
]

# Display the filtered dataframe
higher_f1_meta_df.head()

KeyError: 'meta_f1_score'

In [10]:

# Function to check the presence of certain keywords in the response
def check_keywords(response):
    response_lower = response.lower()
    evidence_extraction = 'extract' in response_lower or 'relevant' in response_lower
    wrote_python_program = 'python' in response_lower
    decomposed = 'decompose' in response_lower or 'decomposition' in response_lower
    return evidence_extraction, wrote_python_program, decomposed

# Apply the function to each response in the Meta DataFrame
meta_keyword_checks = cleaned_meta_results_df['response'].apply(check_keywords)

# Create separate columns for each keyword check
meta_keyword_checks_df = pd.DataFrame(meta_keyword_checks.tolist(), columns=['evidence_extraction', 'wrote_python_program', 'decomposed'])

# Add these columns to the merged results DataFrame
final_merged_results_df_with_keywords = pd.concat([merged_results_df, meta_keyword_checks_df], axis=1)

# Summarize the method column
def summarize_method_details(row):
    summary = []
    if row['evidence_extraction']:
        summary.append("Includes evidence extraction")
    if row['wrote_python_program']:
        summary.append("Writes Python program")
    if row['decomposed']:
        summary.append("Uses decomposition")
    return "; ".join(summary) if summary else "No specific method details found"

final_merged_results_df_with_keywords['method_summary'] = final_merged_results_df_with_keywords.apply(summarize_method_details, axis=1)

# Display the dataframe with keyword checks and method summary
final_merged_results_df_with_keywords.head()

,question,response,f1_score,cot_response,evidence_extraction,wrote_python_program,decomposed,method_summary
0,What were the voting results of the 1975 North...,**Problem Understanding:**\n1. **Determine the...,55.555556,Reasoning: To determine the voting results of ...,True,False,False,Includes evidence extraction
1,What seasons did Faye appear for Hull City?,**Problem Understanding:**\n1. **Determine the...,16.666667,Reasoning: To determine the seasons Faye appea...,True,False,False,Includes evidence extraction
2,When and in which club and league did Kazunari...,**Problem Understanding:**\n1. **Determine the...,52.631579,Reasoning: To determine when and where Kazunar...,True,False,False,Includes evidence extraction
3,What roles did Sandra Peabody play in Tarot an...,**Problem Understanding:**\n1. Determine the O...,18.181818,Reasoning: To determine the roles Sandra Peabo...,True,False,False,Includes evidence extraction
4,What roles did Christian Cooke play in 2009?,**Problem Understanding:**\n1. Determine the O...,34.782609,Reasoning: To determine the roles Christian Co...,True,False,False,Includes evidence extraction

In [12]:

# Select the required columns for the new CSV file
selected_columns_df = final_merged_results_df_with_keywords[
    ['question', 'f1_score', 'cot_f1_score', 'decomp_f1_score', 
     'response', 'cot_response', 'decomp_response', 'answer', 
     'evidence_extraction', 'wrote_python_program', 'decomposed']
]

# Filter the rows where Meta has higher F1 scores compared to CoT and Decomposition
higher_f1_meta_df_selected = selected_columns_df[
    (selected_columns_df['f1_score'] > selected_columns_df['cot_f1_score']) & 
    (selected_columns_df['f1_score'] > selected_columns_df['decomp_f1_score'])
]

# Save the filtered DataFrame to a new CSV file
filtered_output_file_path = 'filtered_selected_columns_results.csv'
higher_f1_meta_df_selected.to_csv(filtered_output_file_path, index=False)

# Display the filtered dataframe
higher_f1_meta_df_selected.head()

KeyError: "['cot_f1_score', 'decomp_f1_score', 'decomp_response', 'answer'] not in index"

In [21]:
import pandas as pd

# Function to classify responses based on specific keywords for approaches
def classify_approaches(response):
    response = response.lower()
    classes = []
    
    # Check for 'extract' related keywords
    extract_keywords = ['extract', 'evidence', 'extracting', 'identify relevant rows']
    if any(keyword in response for keyword in extract_keywords):
        classes.append('extract')
        
    # Check for 'decompose' related keywords
    decompose_keywords = ['sub-problems', 'decompose', 'decomposing', 'subproblems']
    if any(keyword in response for keyword in decompose_keywords):
        classes.append('decompose')
        
    # Check for 'python' related keywords strictly
    python_keywords = ['print', 'import', 'def', 'return', 'code', '# done']
    if any(keyword in response.split() for keyword in python_keywords):
        classes.append('python')
        
    # Check for 'cot' related keywords
    cot_keywords = ['chain of thought', 'reasoning', 'chain-of-thought']
    if any(keyword in response for keyword in cot_keywords):
        classes.append('cot')
    
    return classes

# Load the CSV file
file_path = '/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/fetaqa/fetaqa_meta_results.csv'
meta_results_df = pd.read_csv(file_path)

# Apply the refined classification function to the meta responses
meta_results_df['approach_classes'] = meta_results_df['response'].apply(classify_approaches)
decomposition_results_df = pd.read_csv('/Users/harshavardhank/Desktop/Code/UPenn/TTQA-Recasting/Benchmark/src/scripts/models/responses/New/fetaqa/fetaqa_decomposition_results.csv')

# Display the results

meta_results_df[['question', 'response', 'approach_classes']]

,question,response,approach_classes
0,What were the voting results of the 1975 North...,**Problem Understanding:**\n1. **Determine the...,"[extract, cot]"
1,What seasons did Faye appear for Hull City?,**Problem Understanding:**\n1. **Determine the...,"[extract, cot]"
2,When and in which club and league did Kazunari...,**Problem Understanding:**\n1. **Determine the...,"[extract, cot]"
3,What roles did Sandra Peabody play in Tarot an...,**Problem Understanding:**\n1. Determine the O...,"[extract, cot]"
4,What roles did Christian Cooke play in 2009?,**Problem Understanding:**\n1. Determine the O...,"[extract, cot]"
...,...,...,...
1576,What was the best achievement of Scott Pye in ...,**Problem Understanding:**\n1. Determine the O...,"[extract, decompose, cot]"
1577,What was the outcome of the 2009 Election and ...,**Problem Understanding:**\n1. Determine the O...,"[extract, cot]"
1578,How did Kelly-Ann Baptiste fare at the 2009 wo...,**Problem Understanding:**\n1. Determine the O...,"[extract, cot]"
1579,What roles did Kaya Scodelario play in 2014-20...,**Problem Understanding:**\n1. **Determine the...,"[extract, decompose, cot]"
1580,What is the pixel aspect ratio for the 480 and...,**Problem Understanding:**\n\n1. **Determine t...,"[extract, cot]"

In [26]:


# Redefine the classify_approaches function with correct signature
def classify_approaches(response):
    response = response.lower()
    classes = []
    
    # Check for 'extract' related keywords
    extract_keywords = ['extract', 'evidence', 'extracting', 'identify relevant rows']
    if any(keyword in response for keyword in extract_keywords):
        classes.append('extract')
        
    # Check for 'decompose' related keywords
    decompose_keywords = ['sub-problems', 'decompose', 'decomposing', 'subproblems']
    if any(keyword in response for keyword in decompose_keywords):
        classes.append('decompose')
        
    # Check for 'python' related keywords strictly
    python_keywords = ['print', 'import', 'def', 'return', 'code', '# done']
    if any(keyword in response.split() for keyword in python_keywords):
        classes.append('python')
        
    # Check for 'cot' related keywords
    cot_keywords = ['chain of thought', 'reasoning', 'chain-of-thought']
    if any(keyword in response for keyword in cot_keywords):
        classes.append('cot')
    
    return classes

# Recalculate approach_classes in case they were not saved correctly in the dataframe
meta_results_df['approach_classes'] = meta_results_df['response'].apply(classify_approaches)

# Extract relevant columns from each dataframe
meta_df = meta_results_df[['question', 'response', 'f1_score', 'approach_classes']]
decomposition_df = decomposition_results_df[['question', 'response', 'f1_score']]
cot_df = cot_results_df[['question', 'response', 'f1_score']]

# Rename columns to differentiate between responses and scores
meta_df = meta_df.rename(columns={'response': 'meta_response', 'f1_score': 'meta_f1_score'})
decomposition_df = decomposition_df.rename(columns={'response': 'decomposition_response', 'f1_score': 'decomposition_f1_score'})
cot_df = cot_df.rename(columns={'response': 'cot_response', 'f1_score': 'cot_f1_score'})

# Merge dataframes on the question column
merged_df = meta_df.merge(decomposition_df, on='question').merge(cot_df, on='question')

# Filter rows where Meta scores higher F1 score than CoT and Decomposition
filtered_df = merged_df[(merged_df['meta_f1_score'] > merged_df['decomposition_f1_score']) & (merged_df['meta_f1_score'] > merged_df['cot_f1_score'])]

# Select and display relevant columns
result_df = filtered_df[['question', 'meta_response', 'meta_f1_score', 'approach_classes', 'decomposition_response', 'decomposition_f1_score', 'cot_response', 'cot_f1_score']]



result_df['approach_classes'] = result_df['meta_response'].apply(classify_approaches)

result_df.head()

,question,meta_response,meta_f1_score,approach_classes,decomposition_response,decomposition_f1_score,cot_response,cot_f1_score
0,What were the voting results of the 1975 North...,**Problem Understanding:**\n1. **Determine the...,55.555556,"[extract, cot]","```json\n{\n ""decomposition"": {\n ""sq1"": ""Ide...",26.666667,Reasoning: To determine the voting results of ...,26.666667
7,Who set the fastest average in Megaminx?,**Problem Understanding:**\n1. Determine the O...,31.578947,"[extract, cot]",decomposition: |\n sq1: What is the name ...,22.222222,Reasoning: To find who set the fastest average...,22.222222
8,How's Huang Yu-ting doing in the 2009 World Ga...,**Problem Understanding:**\n1. Determine the O...,42.105263,"[extract, cot]","```json\n{\n ""decomposition"": {\n ""sq1"": ""Ide...",30.303030,Reasoning: To determine Huang Yu-ting's perfor...,6.451613
11,"In the 86th United States Congress, What date ...",**Problem Understanding:**\n1. Determine the O...,35.897436,"[extract, cot]",decomposition: |\n sq1. Identify the row ...,31.578947,Reasoning: To determine the end of Richard M. ...,31.578947
14,Who finished 2nd at the 2014 Commonwealth game...,**Problem Understanding:**\n1. Determine the O...,31.578947,"[extract, cot]",```json\n decomposition: |\n sq1. What was...,22.222222,Reasoning: To find who finished 2nd at the 201...,22.222222

In [ ]:
# Extract a sample of the filtered DataFrame for testing
filtered_df_higher_sample = filtered_df_higher.head(5)

# Merge the sample DataFrame with the original meta_results_df to include the 'answer_extraction' column
comparison_df_higher_sample = filtered_df_higher_sample.merge(meta_results_df[['question', 'answer', 'answer_extraction']], on='question')
comparison_df_higher_sample = comparison_df_higher_sample.merge(decomposition_results_df[['question', 'output']], on='question', suffixes=('', '_decomposition'))
comparison_df_higher_sample = comparison_df_higher_sample.merge(cot_results_df[['question', 'output']], on='question', suffixes=('_decomposition', '_cot'))

# Fix suffix issues manually
comparison_df_higher_sample = comparison_df_higher_sample.rename(columns={'output_decomposition': 'decomposition_output', 'output_cot': 'cot_output'})

# Reorder the columns for better readability
comparison_df_higher_sample = comparison_df_higher_sample[['question', 'meta_response', 'meta_f1_score', 'approach_classes', 'decomposition_response', 'decomposition_f1_score', 'decomposition_output', 'cot_response', 'cot_f1_score', 'cot_output', 'answer', 'answer_extraction']]

# Display the sample DataFrame
comparison_df_higher_sample.head()